/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import AppPackage.AnimationClass;
import static interfaz.Nuevo_PumpTienda.apellido;
import static interfaz.Nuevo_PumpTienda.correo;
import static interfaz.Nuevo_PumpTienda.id;
import static interfaz.Nuevo_PumpTienda.idBiblioteca;
import static interfaz.Nuevo_PumpTienda.nacimiento;
import static interfaz.Nuevo_PumpTienda.nombre;
import static interfaz.Nuevo_PumpTienda.pass;
import static interfaz.Pump_It.apellido;
import static interfaz.Pump_It.correo;
import static interfaz.Pump_It.id;
import static interfaz.Pump_It.idBiblioteca;
import static interfaz.Pump_It.nacimiento;
import static interfaz.Pump_It.nombre;
import static interfaz.Pump_It.pass;
import static interfaz.Verificar.AP;
import static interfaz.Verificar.IDbiblio;
import static interfaz.Verificar.codigo;
import static interfaz.Verificar.contraseña;
import static interfaz.Verificar.email;
import static interfaz.Verificar.fech_nac;
import static interfaz.Verificar.nombre;
import java.awt.Color;
import java.awt.Font;
import java.awt.Rectangle;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author admin
 */
public class Foro extends javax.swing.JFrame {

    /**
     * Creates new form Foro
     */
    public Foro() {
        initComponents();
        open();
        getContentPane().setBackground(Color.darkGray);
        m = (DefaultTableModel)dgvForo.getModel();
        llenarTBL();
        JTableHeader th; 
        th = dgvForo.getTableHeader(); 
        Font fuente = new Font("Myriad Pro", Font.ITALIC, 20); 
        th.setFont(fuente); 
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono5.png")).getImage() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnLibreria = new javax.swing.JButton();
        btnTienda = new javax.swing.JButton();
        btnForo = new javax.swing.JButton();
        btnCuenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgvForo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnYes = new javax.swing.JButton();
        txtTema = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtComentario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBus = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtPass1 = new javax.swing.JPasswordField();
        txtPass2 = new javax.swing.JPasswordField();
        txtBiblio = new javax.swing.JTextField();
        txtCE = new javax.swing.JTextField();
        lblFondoLogin1 = new javax.swing.JLabel();
        btnAcep = new javax.swing.JButton();
        lblUsua = new javax.swing.JLabel();
        lblreg = new javax.swing.JLabel();
        lblAP = new javax.swing.JLabel();
        lblFechNac = new javax.swing.JLabel();
        lblContra1 = new javax.swing.JLabel();
        lblContra2 = new javax.swing.JLabel();
        lblBiblio = new javax.swing.JLabel();
        lblCE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Foro");
        setMaximumSize(new java.awt.Dimension(1160, 600));
        setMinimumSize(new java.awt.Dimension(1160, 600));
        setName("Foro"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1160, 600));
        setSize(new java.awt.Dimension(1160, 600));
        getContentPane().setLayout(null);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnLibreria.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        btnLibreria.setForeground(new java.awt.Color(255, 153, 51));
        btnLibreria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Bag-icon.png"))); // NOI18N
        btnLibreria.setText("Librería");
        btnLibreria.setFocusable(false);
        btnLibreria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLibreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibreriaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLibreria);

        btnTienda.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        btnTienda.setForeground(new java.awt.Color(255, 153, 51));
        btnTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Basket-icon.png"))); // NOI18N
        btnTienda.setText("Tienda");
        btnTienda.setFocusable(false);
        btnTienda.setIconTextGap(6);
        btnTienda.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiendaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTienda);

        btnForo.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        btnForo.setForeground(new java.awt.Color(255, 153, 51));
        btnForo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Chat-6-icon.png"))); // NOI18N
        btnForo.setText("Foro");
        btnForo.setEnabled(false);
        btnForo.setFocusable(false);
        btnForo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToolBar1.add(btnForo);

        btnCuenta.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        btnCuenta.setForeground(new java.awt.Color(255, 153, 51));
        btnCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Settings-2-icon.png"))); // NOI18N
        btnCuenta.setText("Cuenta");
        btnCuenta.setFocusable(false);
        btnCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCuenta);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 1047, 80);

        dgvForo.setBackground(new java.awt.Color(51, 51, 51));
        dgvForo.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        dgvForo.setForeground(new java.awt.Color(255, 153, 51));
        dgvForo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdTema", "Tema", "Usuario", "Comentario"
            }
        ));
        jScrollPane1.setViewportView(dgvForo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 91, 980, 286);

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Tema:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(46, 408, 36, 15);

        btnYes.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnYes.setForeground(new java.awt.Color(255, 153, 51));
        btnYes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Chat-icon.png"))); // NOI18N
        btnYes.setText("Comentar");
        btnYes.setContentAreaFilled(false);
        btnYes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnYes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Chat-icon (2).png"))); // NOI18N
        btnYes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Chat-icon (1).png"))); // NOI18N
        btnYes.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Chat-icon (1).png"))); // NOI18N
        btnYes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Chat-icon (2).png"))); // NOI18N
        btnYes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });
        getContentPane().add(btnYes);
        btnYes.setBounds(446, 432, 97, 104);

        txtTema.setBackground(new java.awt.Color(51, 51, 51));
        txtTema.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtTema.setForeground(new java.awt.Color(255, 255, 255));
        txtTema.setCaretColor(new java.awt.Color(255, 153, 0));
        getContentPane().add(txtTema);
        txtTema.setBounds(100, 405, 318, 21);

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Comentario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 432, 72, 15);

        txtComentario.setBackground(new java.awt.Color(51, 51, 51));
        txtComentario.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtComentario.setForeground(new java.awt.Color(255, 255, 255));
        txtComentario.setCaretColor(new java.awt.Color(255, 153, 0));
        getContentPane().add(txtComentario);
        txtComentario.setBounds(100, 432, 318, 104);

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Buscar actividad en el foro:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(701, 408, 157, 15);

        txtBus.setBackground(new java.awt.Color(51, 51, 51));
        txtBus.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtBus.setForeground(new java.awt.Color(255, 153, 51));
        getContentPane().add(txtBus);
        txtBus.setBounds(606, 458, 366, 26);

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("Codigo de actividad:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(711, 432, 120, 15);

        jButton1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Search-icon (2).png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(750, 490, 81, 75);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 389, 980, 10);

        txtNombre.setBackground(new java.awt.Color(51, 51, 51));
        txtNombre.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(1160, 70, 140, 30);

        txtApellido.setBackground(new java.awt.Color(51, 51, 51));
        txtApellido.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellido);
        txtApellido.setBounds(1160, 130, 140, 30);

        txtMes.setBackground(new java.awt.Color(51, 51, 51));
        txtMes.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtMes.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtMes);
        txtMes.setBounds(1160, 190, 140, 30);

        txtPass1.setText("jPasswordField1");
        txtPass1.setVisible(false);
        txtPass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPass1FocusLost(evt);
            }
        });
        getContentPane().add(txtPass1);
        txtPass1.setBounds(1160, 250, 140, 30);

        txtPass2.setText("jPasswordField1");
        txtPass2.setVisible(false);
        txtPass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPass2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPass2FocusLost(evt);
            }
        });
        txtPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass2);
        txtPass2.setBounds(1160, 310, 140, 30);

        txtBiblio.setBackground(new java.awt.Color(51, 51, 51));
        txtBiblio.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtBiblio.setForeground(new java.awt.Color(255, 255, 255));
        txtBiblio.setEnabled(false);
        getContentPane().add(txtBiblio);
        txtBiblio.setBounds(1160, 370, 140, 30);

        txtCE.setBackground(new java.awt.Color(51, 51, 51));
        txtCE.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtCE.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCE);
        txtCE.setBounds(1160, 430, 140, 30);

        lblFondoLogin1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblFondoLogin1.setForeground(new java.awt.Color(255, 255, 255));
        lblFondoLogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-negro-detalles-naranjas_1408-69.jpg"))); // NOI18N
        lblFondoLogin1.setText("z");
        lblFondoLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFondoLogin1MouseClicked(evt);
            }
        });
        getContentPane().add(lblFondoLogin1);
        lblFondoLogin1.setBounds(1160, 0, 200, 590);

        btnAcep.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnAcep.setForeground(new java.awt.Color(255, 153, 51));
        btnAcep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plus-icon.png"))); // NOI18N
        btnAcep.setText("Aceptar");
        btnAcep.setContentAreaFilled(false);
        btnAcep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcepActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcep);
        btnAcep.setBounds(1160, 470, 100, 80);

        lblUsua.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblUsua.setForeground(new java.awt.Color(255, 255, 255));
        lblUsua.setText("Usuario:");
        getContentPane().add(lblUsua);
        lblUsua.setBounds(1160, 40, 80, 20);

        lblreg.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        lblreg.setForeground(new java.awt.Color(255, 255, 255));
        lblreg.setText("Cuenta.");
        getContentPane().add(lblreg);
        lblreg.setBounds(1160, 0, 170, 40);

        lblAP.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblAP.setForeground(new java.awt.Color(255, 255, 255));
        lblAP.setText("Nombre Completo:");
        getContentPane().add(lblAP);
        lblAP.setBounds(1160, 110, 130, 15);

        lblFechNac.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblFechNac.setForeground(new java.awt.Color(255, 255, 255));
        lblFechNac.setText("Fecha de nacimiento:");
        getContentPane().add(lblFechNac);
        lblFechNac.setBounds(1160, 170, 150, 15);

        lblContra1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblContra1.setForeground(new java.awt.Color(255, 255, 255));
        lblContra1.setText("Contraseña:");
        getContentPane().add(lblContra1);
        lblContra1.setBounds(1160, 230, 70, 15);

        lblContra2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblContra2.setForeground(new java.awt.Color(255, 255, 255));
        lblContra2.setText("Confirma contraseña:");
        getContentPane().add(lblContra2);
        lblContra2.setBounds(1160, 290, 140, 15);

        lblBiblio.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblBiblio.setForeground(new java.awt.Color(255, 255, 255));
        lblBiblio.setText("IdBiblioteca:");
        getContentPane().add(lblBiblio);
        lblBiblio.setBounds(1160, 350, 110, 15);

        lblCE.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblCE.setForeground(new java.awt.Color(255, 255, 255));
        lblCE.setText("Correo electronico:");
        getContentPane().add(lblCE);
        lblCE.setBounds(1160, 410, 120, 15);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLibreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibreriaActionPerformed
        Pump_It.id=id;
        Pump_It.nombre=nombre;
        Pump_It.apellido=apellido;
        Pump_It.nacimiento=nacimiento;
        Pump_It.pass=pass;
        Pump_It.idBiblioteca=idBiblioteca;
        Pump_It.correo=correo;
        Pump_It ventana = new Pump_It();
        ventana.show(true);
        this.dispose();
        
    }//GEN-LAST:event_btnLibreriaActionPerformed

    private void btnTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiendaActionPerformed
        Nuevo_PumpTienda.id=id;
        Nuevo_PumpTienda.nombre=nombre;
        Nuevo_PumpTienda.apellido=apellido;
        Nuevo_PumpTienda.nacimiento=nacimiento;
        Nuevo_PumpTienda.pass=pass;
        Nuevo_PumpTienda.idBiblioteca=idBiblioteca;
        Nuevo_PumpTienda.correo=correo;
        Nuevo_PumpTienda ventana = new Nuevo_PumpTienda();
        ventana.show(true);
        this.dispose();
    }//GEN-LAST:event_btnTiendaActionPerformed

     public void hashToTable(){
        m.setRowCount(0);
        Object O[] = new Object[4];
        for (int i = 0; i < G.length; i++) {
            if(G[i]==null){
                O[0] = " ";
                O[1] = " ";
                O[2] = " ";
                O[3] = " ";
            }else{
                //System.out.println("Valores del objeto a añadir:"+Z[i].getIdTema()+"---"+Z[i].getTema()+Z[i].getUsuario()+Z[i].getComentario());
                O[0] = G[i].getIdTema();
                O[1] = G[i].getTema();
                O[2] = G[i].getUsuario();
                O[3] = G[i].getComentario();
         
            
            }
            m.addRow(O);
           // System.out.println("Valores del objeto a añadir:"+Z[i].getIdTema()+"---"+Z[i].getTema()+Z[i].getUsuario()+Z[i].getComentario());
            
        }
     }//iwi
     
      private void open(){
        G = new Foro2[1000];
        try {
            FileInputStream fi = new FileInputStream("foros.fs");
            ObjectInputStream fib = new ObjectInputStream(fi);
            while (fib.read() == -1) {
                Foro2 g = (Foro2) fib.readObject();
                addGame(g);
            }
            hashToTable();
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
    }//open
     
     
    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        String ola="120";
        int n=(int)(Math.random()*1000);
        ola2=ola+n+"";
        Foro2 g = new Foro2();
        g.setIdTema(ola2);
        //System.out.println("ID del objeto g: "+g.getIdTema());
        g.setTema(txtTema.getText());
        //System.out.println("Tema: "+g.getTema());
        g.setUsuario(id);
        g.setComentario(txtComentario.getText());
        if(g.getIdTema().equals("")){showMessageDialog(this,"ID no valida, vacio"); return;}
        if(buscar(g.getIdTema())!=-1){showMessageDialog(this,"ID no valida, -1"); return;}
        System.out.println("--------------------------AddGame----------------------------");
        addGame(g);
        System.out.println("--------------------------fin deAddGame----------------------------");
        System.out.println("--------------------------Save----------------------------");
        save();
        System.out.println("--------------------------fin del Save----------------------------");
        System.out.println("--------------------------Open----------------------------");
        open();
        System.out.println("--------------------------Fin del open----------------------------");
        m.setRowCount(0);
        hashToTable();
        encontrar(g.getIdTema());
        String cad="";
        try{
            conectar();
            cad = "insert into FORO(IdForo,TEMA, Usuario, COMENTARIO) Values('"
                            + ola2 + "','"+ txtTema.getText() +"','"+ id +"','"+ txtComentario.getText() +"')";
                    st.execute(cad);
                    //st.executeUpdate(cad);
                    System.out.println("inserted");
                    st.close();
                   //addGame(g);
                   // save();
                    //llenarTBL();
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(RegistrarClienteException.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_btnYesActionPerformed
    
private void addGame(Foro2 g){
        if(g==null)return;
        if(hash(g.getIdTema())==-1){showMessageDialog(this,"ID no valida"); return;}
        int pos = hash(g.getIdTema());
        while(G[pos]!=null)pos++;
        if(pos>=G.length-1) {showMessageDialog(this,"ID error"); return;}
        G[pos]=g;
    }//addToHash
        private void save(){
        try {
           FileOutputStream fo=new FileOutputStream("foros.fs");
            ObjectOutputStream fob=new ObjectOutputStream(fo);
            for(int i=0;i<G.length;i++){
                fob.writeObject(G[i]);
                System.out.println(G[i]);
                fob.flush();
            }
        } catch (FileNotFoundException ex) {} catch (IOException ex) { }
    }//save

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         encontrar(txtBus.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        /*  int r = 0;
        String h = "";
        int b = (int) (Math.random() * 100);
        h = "700" + b + "";
        txtBiblio.setText(h);*/
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) && (c < ',' || c > '.')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtPass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass1FocusGained
        txtPass1.setEchoChar((char)0);

    }//GEN-LAST:event_txtPass1FocusGained

    private void txtPass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass1FocusLost
        txtPass1.setEchoChar('*');
    }//GEN-LAST:event_txtPass1FocusLost

    private void txtPass2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass2FocusGained
        txtPass2.setEchoChar((char)0);
    }//GEN-LAST:event_txtPass2FocusGained

    private void txtPass2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass2FocusLost
        txtPass2.setEchoChar('*');
    }//GEN-LAST:event_txtPass2FocusLost

    private void txtPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass2ActionPerformed

    private void lblFondoLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoLogin1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFondoLogin1MouseClicked

    private void btnAcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcepActionPerformed
        try{
            String pwd = new String(txtPass1.getPassword());
            String pwd2 = new String(txtPass2.getPassword());
            if(pwd.equals(pwd2)){
                conectar();
                String nuevoNombre = txtNombre.getText();//usuario
                String nuevoApellido = txtApellido.getText();//nombre del usuario
                String nuevoNacimiento = txtMes.getText();
                String nuevoCE = txtCE.getText();
                String nuevoPass = txtPass1.getText();
                String sql;
                sql="update USUARIOS set nombre='"+nuevoNombre+"',apellido='"+nuevoApellido+"' ,nacimiento='"+nuevoNacimiento+"',pass='"+nuevoPass+",correo='"+nuevoCE+"'where nombre='"+nuevoNombre+"'";
                st.executeUpdate(sql);
            }else{showMessageDialog(this,"Las contraseñas no coinciden.");}
        }catch(SQLException ex){
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAcepActionPerformed

    private void btnCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaActionPerformed
        txtNombre.setText(nombre);
         txtApellido.setText(apellido);
         txtMes.setText(nacimiento);
         txtBiblio.setText(idBiblioteca);
         txtCE.setText(correo);
         txtPass1.setText(pass);
        
        AnimationClass lbl11 = new AnimationClass();
        lbl11.jLabelXLeft(1160,960,10,5, lblFondoLogin1);
        AnimationClass txt11 = new AnimationClass();
        txt11.jTextFieldXLeft(1160,990,10,5, txtNombre);
        AnimationClass txt22 = new AnimationClass();
        txt22.jTextFieldXLeft(1160,990,10,5, txtApellido);
        AnimationClass lbl22 = new AnimationClass();
        lbl22.jLabelXLeft(1160,980,10,5, lblreg);
        AnimationClass lbl33 = new AnimationClass();
        lbl33.jLabelXLeft(1160,990,10,5, lblUsua);
        AnimationClass btn11 = new AnimationClass();
        btn11.jButtonXLeft(1160,1010,10,5, btnAcep);
        AnimationClass lbl44 = new AnimationClass();
        lbl44.jLabelXLeft(1160,990,10,5, lblAP);
        AnimationClass lbl55 = new AnimationClass();
        lbl55.jLabelXLeft(1160,990,10,5, lblFechNac);
        AnimationClass lbl66 = new AnimationClass();
        lbl66.jLabelXLeft(1160,990,10,5, lblContra1);
        AnimationClass lbl77 = new AnimationClass();
        lbl77.jLabelXLeft(1160,990,10,5, lblContra2);
        txtPass1.setVisible(true);
        txtPass2.setVisible(true);
        AnimationClass lbl88 = new AnimationClass();
        lbl88.jLabelXLeft(1160,990,10,5, lblBiblio);
        AnimationClass lbl99 = new AnimationClass();
        lbl99.jLabelXLeft(1160,990,10,5, lblCE);
        AnimationClass lbl1010 = new AnimationClass();
        AnimationClass txtb = new AnimationClass();
        txtb.jTextFieldXLeft(1160,1040,10,5, txtMes);
        AnimationClass txtd = new AnimationClass();
        txtd.jTextFieldXLeft(1160,990,10,5, txtBiblio);
        AnimationClass txte = new AnimationClass();
        txte.jTextFieldXLeft(1160,990,10,5, txtCE);
        AnimationClass psw1 = new AnimationClass();
        psw1.jPasswordFieldXLeft(1160, 990, 10, 5, txtPass1);
        AnimationClass psw2 = new AnimationClass();
        psw2.jPasswordFieldXLeft(1160, 990, 10,5, txtPass2);
        
        //izq
        AnimationClass lbl1 = new AnimationClass();
        lbl1.jLabelXRight(960,1160,10,5, lblFondoLogin1);
        AnimationClass txt1 = new AnimationClass();
        txt1.jTextFieldXRight(990,1160,10,5, txtNombre);
        AnimationClass txt2 = new AnimationClass();
        txt1.jTextFieldXRight(990,1160,10,5, txtApellido);
        AnimationClass lbl2 = new AnimationClass();
        lbl2.jLabelXRight(980,1160,10,5, lblreg);
        AnimationClass lbl3 = new AnimationClass();
        lbl3.jLabelXRight(990,1160,10,5, lblUsua);
        AnimationClass btn1 = new AnimationClass();
        btn1.jButtonXRight(1010,1160,10,5, btnAcep);
        AnimationClass lbl4 = new AnimationClass();
        lbl4.jLabelXRight(990,1160,10,5, lblAP);
        AnimationClass lbl5 = new AnimationClass();
        lbl5.jLabelXRight(990,1160,10,5, lblFechNac);
        AnimationClass lbl6 = new AnimationClass();
        lbl6.jLabelXRight(990,1160,10,5, lblContra1);
        AnimationClass lbl7 = new AnimationClass();
        lbl7.jLabelXRight(990,1160,10,5, lblContra2);
        //txtPass1.setVisible(false);
        //txtPass2.setVisible(false);
        AnimationClass lbl8 = new AnimationClass();
        lbl8.jLabelXRight(990,1160,10,5, lblBiblio);
        AnimationClass lbl9 = new AnimationClass();
        lbl9.jLabelXRight(990,1160,10,5, lblCE);
        AnimationClass lbl10 = new AnimationClass();
        AnimationClass txtbb = new AnimationClass();
        txtbb.jTextFieldXRight(1040,1160,10,5, txtMes);
        AnimationClass txtdd = new AnimationClass();
        txtdd.jTextFieldXRight(990,1160,10,5, txtBiblio);
        AnimationClass txtee = new AnimationClass();
        txtee.jTextFieldXRight(990,1160,10,5, txtCE);
        AnimationClass psw11 = new AnimationClass();
        psw11.jPasswordFieldXRight(990,1160,10,5, txtPass1);
        AnimationClass psw22 = new AnimationClass();
        psw22.jPasswordFieldXRight(990,1160,10,5, txtPass2);
    }//GEN-LAST:event_btnCuentaActionPerformed

     public boolean encontrar(String id){
        hashToTable();
        int pos = buscar(id);
        if(pos!=-1){
            Foro2 g = G[pos];
            dgvForo.setRowSelectionInterval(pos, pos);
            dgvForo.scrollRectToVisible(new Rectangle(dgvForo.getCellRect(pos, 0, true)));
            //llenarCampos(g);
           
            return true;
        }else{return false;}
    }//encontrar
//          private void llenarCampos(Foro1 g){
//        txtID.setText(g.getID());
//        txtName.setText(g.getName());
//        txtGenre.setText(g.getGenre());
//        txtPlatform.setText(g.getPlatform());
//        txtRate.setValue(g.getRateing());
//    }//llenarCampos
        
    private void llenarTBL() {
//        try {
//            conectar();
//            Object O[] = new Object[4];
//            st = conn.createStatement();
//            st.execute("select IdForo, TEMA, Usuario, COMENTARIO from FORO");
//            rs = st.getResultSet();
//            m.setRowCount(0);
//            Foro1 f = new Foro1();
//            if (rs != null && rs.isFirst() == false) {
//                while (rs.next()) {
//                    O[0] = rs.getString("IdForo");
//                    O[1] = rs.getString("TEMA");
//                    O[2] = rs.getString("Usuario");
//                    O[3] = rs.getString("COMENTARIO");
//                    m.addRow(O);                   
//                }
//            } else {
//                showMessageDialog(this, "Error, no se encontraron registros");
//                st.close();
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }
    
        private int buscar(String id){//retorna la posicion, si no existe: retorna -1
        if(hash(id)==-1)return -1;
        int pos = hash(id);
        while(G[pos]!=null && !G[pos].getIdTema().equals(id)) {
            pos++;
            if(pos>=G.length-1){break;}
        }
        if(G[pos]==null) return -1;
        if(!G[pos].getIdTema().equals(id))return -1;
        return pos;
    }//buscar
    

    
private int hash(String cad){
        System.out.println(cad+"parametro del hash()");
         System.out.println(cad.substring(cad.length()-2)+"valor que retorna el hash");
        return Integer.parseInt(cad.substring(cad.length()-2));
}//elhash
    
     public void conectar() {
        try {

            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");

        } catch (ClassNotFoundException cnfex) {

            System.out.println("Problema al cargar o "
                    + "registrar:  MS Access JDBC driver");
            cnfex.printStackTrace();
        }

        try {
            conn = DriverManager.getConnection(dbURL);
            st = conn.createStatement();
            System.out.println("Conexion establecida");

        } catch (SQLException ex) {

            System.out.println("error de conexion");
        }
        System.out.println("Proceso de conexión finalizado.");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foro().setVisible(true);
            }
        });
    }
    public static String ola2="";

    private Foro2 G[] = new Foro2[1000];
    private Statement st;
    private ResultSet rs;
    private Connection conn = null;
    private String msAccDB = "C:\\Users\\marva\\Dropbox (Tecnológico)\\ED\\Pump_it!\\src\\Data\\Pump_ItDB.accdb";
    private String dbURL = "jdbc:ucanaccess://" + msAccDB;
    DefaultTableModel m;
    private  String IdUsuario;
    public static String id="";
    public static String nombre="";
    public static String apellido="";
    public static String nacimiento="";
    public static String pass="";
    public static String idBiblioteca="";
    public static String correo="";
    public static String usu1="";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcep;
    private javax.swing.JButton btnCuenta;
    private javax.swing.JButton btnForo;
    private javax.swing.JButton btnLibreria;
    private javax.swing.JButton btnTienda;
    private javax.swing.JButton btnYes;
    private javax.swing.JTable dgvForo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAP;
    private javax.swing.JLabel lblBiblio;
    private javax.swing.JLabel lblCE;
    private javax.swing.JLabel lblContra1;
    private javax.swing.JLabel lblContra2;
    private javax.swing.JLabel lblFechNac;
    private javax.swing.JLabel lblFondoLogin1;
    private javax.swing.JLabel lblUsua;
    private javax.swing.JLabel lblreg;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBiblio;
    private javax.swing.JTextField txtBus;
    private javax.swing.JTextField txtCE;
    private javax.swing.JTextField txtComentario;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JPasswordField txtPass2;
    private javax.swing.JTextField txtTema;
    // End of variables declaration//GEN-END:variables
}