/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Marval
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        getContentPane().setBackground(Color.darkGray);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono5.png")).getImage());
        while(true){
            AnuncioAdelanteAuto();
            AnuncioAtrasAuto();
        }
    }

    public void AnuncioAdelanteAuto() {
        Timer t = new Timer();
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                AnuncioAdelante();
            }
        };
        t.schedule(task, 3000);
    }

    public void AnuncioAtrasAuto() {
        Timer t = new Timer();
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                AnuncioAtras();
            }
        };
        t.schedule(task, 9000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContra2 = new javax.swing.JLabel();
        lblContra1 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        lblFechNac = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        lblAP = new javax.swing.JLabel();
        txtCE = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblUsua = new javax.swing.JLabel();
        lblCE = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtBiblio = new javax.swing.JTextField();
        lblBiblio = new javax.swing.JLabel();
        lblCue2 = new javax.swing.JLabel();
        lblCue = new javax.swing.JLabel();
        lblOlv = new javax.swing.JLabel();
        lblOlv2 = new javax.swing.JLabel();
        lblreg = new javax.swing.JLabel();
        btnAcep = new javax.swing.JButton();
        btnThis = new javax.swing.JButton();
        lblUsu = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtcontrasena = new javax.swing.JTextField();
        lblContra = new javax.swing.JLabel();
        btnAcceder = new javax.swing.JButton();
        txtPass1 = new javax.swing.JPasswordField();
        lblFondoLogin = new javax.swing.JLabel();
        txtPass2 = new javax.swing.JPasswordField();
        lblawa = new javax.swing.JLabel();
        lblunu = new javax.swing.JLabel();
        lblFondoLogin1 = new javax.swing.JLabel();
        btnAdelante = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblAnuncio = new javax.swing.JLabel();
        btnPI = new javax.swing.JButton();
        lblgame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1160, 600));
        setPreferredSize(new java.awt.Dimension(1160, 600));
        getContentPane().setLayout(null);

        lblContra2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblContra2.setForeground(new java.awt.Color(255, 255, 255));
        lblContra2.setText("Confirma contraseña:");
        getContentPane().add(lblContra2);
        lblContra2.setBounds(1160, 290, 140, 15);

        lblContra1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblContra1.setForeground(new java.awt.Color(255, 255, 255));
        lblContra1.setText("Contraseña:");
        getContentPane().add(lblContra1);
        lblContra1.setBounds(1160, 230, 70, 15);

        txtMes.setBackground(new java.awt.Color(51, 51, 51));
        txtMes.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtMes.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtMes);
        txtMes.setBounds(1160, 190, 30, 30);

        lblFechNac.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblFechNac.setForeground(new java.awt.Color(255, 255, 255));
        lblFechNac.setText("Fecha de nacimiento:");
        getContentPane().add(lblFechNac);
        lblFechNac.setBounds(1160, 170, 150, 15);

        txtDia.setBackground(new java.awt.Color(51, 51, 51));
        txtDia.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtDia.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtDia);
        txtDia.setBounds(1160, 190, 30, 30);

        lblAP.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblAP.setForeground(new java.awt.Color(255, 255, 255));
        lblAP.setText("Nombre Completo:");
        getContentPane().add(lblAP);
        lblAP.setBounds(1160, 110, 130, 15);

        txtCE.setBackground(new java.awt.Color(51, 51, 51));
        txtCE.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtCE.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCE);
        txtCE.setBounds(1160, 430, 140, 30);

        txtApellido.setBackground(new java.awt.Color(51, 51, 51));
        txtApellido.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellido);
        txtApellido.setBounds(1160, 130, 140, 30);

        lblUsua.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblUsua.setForeground(new java.awt.Color(255, 255, 255));
        lblUsua.setText("Usuario:");
        getContentPane().add(lblUsua);
        lblUsua.setBounds(1160, 40, 80, 20);

        lblCE.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblCE.setForeground(new java.awt.Color(255, 255, 255));
        lblCE.setText("Correo electronico:");
        getContentPane().add(lblCE);
        lblCE.setBounds(1160, 410, 120, 15);

        txtAnio.setBackground(new java.awt.Color(51, 51, 51));
        txtAnio.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtAnio.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtAnio);
        txtAnio.setBounds(1160, 190, 30, 30);

        txtNombre.setBackground(new java.awt.Color(51, 51, 51));
        txtNombre.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(1160, 70, 140, 30);

        txtBiblio.setBackground(new java.awt.Color(51, 51, 51));
        txtBiblio.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtBiblio.setForeground(new java.awt.Color(255, 255, 255));
        txtBiblio.setEnabled(false);
        getContentPane().add(txtBiblio);
        txtBiblio.setBounds(1160, 370, 140, 30);

        lblBiblio.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblBiblio.setForeground(new java.awt.Color(255, 255, 255));
        lblBiblio.setText("IdBiblioteca:");
        getContentPane().add(lblBiblio);
        lblBiblio.setBounds(1160, 350, 110, 15);

        lblCue2.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        lblCue2.setForeground(new java.awt.Color(255, 255, 255));
        lblCue2.setText("Haz click aquí");
        lblCue2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCue2MouseClicked(evt);
            }
        });
        getContentPane().add(lblCue2);
        lblCue2.setBounds(-75, 440, 70, 13);

        lblCue.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblCue.setForeground(new java.awt.Color(255, 255, 255));
        lblCue.setText("¿No tienes cuenta?");
        getContentPane().add(lblCue);
        lblCue.setBounds(-115, 420, 111, 15);

        lblOlv.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblOlv.setForeground(new java.awt.Color(255, 255, 255));
        lblOlv.setText("¿Olvidaste tu contraseña?");
        getContentPane().add(lblOlv);
        lblOlv.setBounds(-155, 370, 150, 15);

        lblOlv2.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        lblOlv2.setForeground(new java.awt.Color(255, 255, 255));
        lblOlv2.setText("Haz click aquí");
        lblOlv2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOlv2MouseClicked(evt);
            }
        });
        getContentPane().add(lblOlv2);
        lblOlv2.setBounds(-75, 390, 70, 13);

        lblreg.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        lblreg.setForeground(new java.awt.Color(255, 255, 255));
        lblreg.setText("Registro de usuarios:");
        getContentPane().add(lblreg);
        lblreg.setBounds(1160, 0, 170, 40);

        btnAcep.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnAcep.setForeground(new java.awt.Color(255, 153, 51));
        btnAcep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plus-icon.png"))); // NOI18N
        btnAcep.setText("Aceptar");
        btnAcep.setContentAreaFilled(false);
        btnAcep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcep.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plus-icon2.png"))); // NOI18N
        btnAcep.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plus-icon (4).png"))); // NOI18N
        btnAcep.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plus-icon (4).png"))); // NOI18N
        btnAcep.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plus-icon2.png"))); // NOI18N
        btnAcep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcepActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcep);
        btnAcep.setBounds(1160, 470, 100, 80);

        btnThis.setBackground(new java.awt.Color(255, 153, 0));
        btnThis.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnThis.setForeground(new java.awt.Color(255, 153, 51));
        btnThis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-2-iconowo.png"))); // NOI18N
        btnThis.setText("Accede a pump It!");
        btnThis.setBorderPainted(false);
        btnThis.setContentAreaFilled(false);
        btnThis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThis.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-2-icon (2).png"))); // NOI18N
        btnThis.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-2-icon2.png"))); // NOI18N
        btnThis.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-2-icon (2).png"))); // NOI18N
        btnThis.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-2-icon (2).png"))); // NOI18N
        btnThis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThisActionPerformed(evt);
            }
        });
        getContentPane().add(btnThis);
        btnThis.setBounds(10, 430, 140, 120);

        lblUsu.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        lblUsu.setForeground(new java.awt.Color(255, 255, 255));
        lblUsu.setText("Usuario:");
        lblUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuMouseClicked(evt);
            }
        });
        getContentPane().add(lblUsu);
        lblUsu.setBounds(-70, 110, 63, 19);

        txtUsuario.setBackground(new java.awt.Color(51, 51, 51));
        txtUsuario.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(-120, 133, 120, 30);

        txtcontrasena.setBackground(new java.awt.Color(51, 51, 51));
        txtcontrasena.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtcontrasena.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtcontrasena);
        txtcontrasena.setBounds(-120, 233, 120, 30);

        lblContra.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        lblContra.setForeground(new java.awt.Color(255, 255, 255));
        lblContra.setText("Contraseña");
        getContentPane().add(lblContra);
        lblContra.setBounds(-90, 210, 88, 19);

        btnAcceder.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnAcceder.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-3-icon (1).png"))); // NOI18N
        btnAcceder.setText("Acceder");
        btnAcceder.setContentAreaFilled(false);
        btnAcceder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcceder.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-3-icon (4).png"))); // NOI18N
        btnAcceder.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-3-icon (5).png"))); // NOI18N
        btnAcceder.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-3-icon (5).png"))); // NOI18N
        btnAcceder.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-3-icon (4).png"))); // NOI18N
        btnAcceder.setVerifyInputWhenFocusTarget(false);
        btnAcceder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcceder);
        btnAcceder.setBounds(-80, 270, 90, 80);

        txtPass1.setText("jPasswordField1");
        txtPass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPass1FocusGained(evt);
            }
        });
        getContentPane().add(txtPass1);
        txtPass1.setBounds(1160, 250, 140, 30);

        lblFondoLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblFondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-negro-detalles-naranjas_1408-69.jpg"))); // NOI18N
        lblFondoLogin.setText("z");
        lblFondoLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFondoLoginMouseClicked(evt);
            }
        });
        getContentPane().add(lblFondoLogin);
        lblFondoLogin.setBounds(-200, 0, 200, 590);
        lblFondoLogin.getAccessibleContext().setAccessibleDescription("");

        txtPass2.setText("jPasswordField1");
        txtPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass2);
        txtPass2.setBounds(1160, 310, 140, 30);

        lblawa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblawa.setForeground(new java.awt.Color(255, 255, 255));
        lblawa.setText("/");
        getContentPane().add(lblawa);
        lblawa.setBounds(1160, 190, 20, 30);

        lblunu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblunu.setForeground(new java.awt.Color(255, 255, 255));
        lblunu.setText("/");
        getContentPane().add(lblunu);
        lblunu.setBounds(1160, 190, 20, 30);

        lblFondoLogin1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblFondoLogin1.setForeground(new java.awt.Color(255, 255, 255));
        lblFondoLogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-negro-detalles-naranjas_1408-69.jpg"))); // NOI18N
        lblFondoLogin1.setText("z");
        lblFondoLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFondoLogin1MouseClicked(evt);
            }
        });
        getContentPane().add(lblFondoLogin1);
        lblFondoLogin1.setBounds(1160, 0, 200, 590);

        btnAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-icon.png"))); // NOI18N
        btnAdelante.setContentAreaFilled(false);
        btnAdelante.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-icon2.png"))); // NOI18N
        btnAdelante.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-icon (3).png"))); // NOI18N
        btnAdelante.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Arrow-Next-icon2.png"))); // NOI18N
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdelante);
        btnAdelante.setBounds(50, 0, 81, 57);

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Back-icon.png"))); // NOI18N
        btnAtras.setContentAreaFilled(false);
        btnAtras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Back-icon2.png"))); // NOI18N
        btnAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Back-icon (2).png"))); // NOI18N
        btnAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Back-icon (2).png"))); // NOI18N
        btnAtras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Back-icon2.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(0, 0, 81, 57);

        lblAnuncio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/0000002217.1920x1080-800x500 (1) (1).png"))); // NOI18N
        lblAnuncio.setMaximumSize(new java.awt.Dimension(1160, 1000));
        lblAnuncio.setMinimumSize(new java.awt.Dimension(1160, 1000));
        lblAnuncio.setPreferredSize(new java.awt.Dimension(1160, 1000));
        getContentPane().add(lblAnuncio);
        lblAnuncio.setBounds(1160, 0, 1960, 590);

        btnPI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aaaaaaa3.png"))); // NOI18N
        btnPI.setContentAreaFilled(false);
        btnPI.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aaaaaaa4.png"))); // NOI18N
        getContentPane().add(btnPI);
        btnPI.setBounds(240, 30, 650, 530);

        lblgame.setFont(new java.awt.Font("Myriad Pro", 0, 36)); // NOI18N
        lblgame.setForeground(new java.awt.Color(255, 102, 0));
        lblgame.setText("\"El juego que buscas, ¡seguro, fácil y rapido!\"");
        getContentPane().add(lblgame);
        lblgame.setBounds(190, 20, 720, 70);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        if (txtUsuario.getText().equals("") && txtcontrasena.getText().equals("")) {
            showMessageDialog(this, "Campos vacíos, verifique los espacios.");
            return;
        }
        String id = "", nombre = "", apellido = "", nacimiento = "", pass = "", idbiblio = "", correo = "";
        try {
            conectar();
            String usuario = txtUsuario.getText();
            String contrasena = txtcontrasena.getText();
            String sql = "select * from USUARIOS where nombre = '" + usuario + "'and pass = '" + contrasena + "'";
            rs = st.executeQuery(sql);
            int count = 0;
            while (rs.next()) {
                count = count + 1;
                id = rs.getString("IdUsuario");
                nombre = rs.getString("nombre");
                apellido = rs.getString("apellido");
                nacimiento = rs.getString("nacimiento");
                pass = rs.getString("pass");
                idbiblio = rs.getString("IdBiblioteca");
                correo = rs.getString("correo");
            }
            if (count == 1) {
                //showMessageDialog(this,"Acceso concedido: ");
                sound.PumpItIntroSound();
                System.out.println("" + rs.toString());
                Pump_It.id = id;
                Pump_It.nombre = nombre;
                Pump_It.apellido = apellido;
                Pump_It.nacimiento = nacimiento;
                Pump_It.pass = pass;
                Pump_It.idBiblioteca = idbiblio;
                Pump_It.correo = correo;
                //sql = "select IdUsuario from USUARIOS where  nombre = '"+usuario+"'and pass = '"+contrasena+"'";
                //st.execute(sql);
                //rs = st.getResultSet();
                //IdUsuario = rs.getString("IdUsuario");
                //lbl1.setText(IdUsuario);//se supone que saque el valor numérico del Id, para poder utilizarlo en futuras acciones.
                Pump_It ventana = new Pump_It();
                ventana.show();
                this.dispose();

                //Aquí va la animación..................
                AnimationClass dis = new AnimationClass();
                dis.jLabelXLeft(0, -100, 40, 10, lblFondoLogin);

            } else if (count > 1) {
                sound.PumpItIntroFailSound();
                showMessageDialog(this, "Usuario duplicado, acceso denegado");

            } else {
                sound.PumpItIntroFailSound();
                showMessageDialog(this, "Usuario inexistente, Acceso denegado");

            }
        } catch (SQLException ex) {
            sound.PumpItIntroFailSound();
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
            showMessageDialog(this, "Usuario inexistente, Acceso denegado");

        }

    }//GEN-LAST:event_btnAccederActionPerformed
    public void conectar() {
        try {

            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");

        } catch (ClassNotFoundException cnfex) {

            System.out.println("Problema al cargar o "
                    + "registrar:  MS Access JDBC driver");
            cnfex.printStackTrace();
        }

        try {
            conn = DriverManager.getConnection(dbURL);
            st = conn.createStatement();
            System.out.println("Conexion establecida");

        } catch (SQLException ex) {

            System.out.println("error de conexion");
        }
        System.out.println("Proceso de conexión finalizado.");
    }
    private void lblFondoLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoLoginMouseClicked

    }//GEN-LAST:event_lblFondoLoginMouseClicked

    private void lblFondoLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoLogin1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFondoLogin1MouseClicked

    private void btnThisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThisActionPerformed
        AnimationClass lbl1 = new AnimationClass();

        lbl1.jLabelXRight(-200, 10, 10, 5, lblFondoLogin);
        AnimationClass txt1 = new AnimationClass();
        txt1.jTextFieldXRight(-120, 45, 10, 5, txtUsuario);
        AnimationClass txt2 = new AnimationClass();
        txt1.jTextFieldXRight(-120, 45, 10, 5, txtcontrasena);
        AnimationClass lbl2 = new AnimationClass();
        lbl2.jLabelXRight(-70, 70, 10, 5, lblUsu);
        AnimationClass lbl3 = new AnimationClass();
        lbl3.jLabelXRight(-120, 70, 10, 5, lblContra);
        AnimationClass btn1 = new AnimationClass();
        btn1.jButtonXRight(-80, 70, 10, 5, btnAcceder);
        AnimationClass lbl4 = new AnimationClass();
        lbl4.jLabelXRight(-155, 30, 10, 5, lblOlv);
        AnimationClass lbl5 = new AnimationClass();
        lbl5.jLabelXRight(-75, 75, 10, 5, lblOlv2);
        AnimationClass lbl6 = new AnimationClass();
        lbl6.jLabelXRight(-115, 50, 10, 5, lblCue);
        AnimationClass lbl7 = new AnimationClass();
        lbl7.jLabelXRight(-75, 75, 10, 5, lblCue2);
        AnimationClass btn2 = new AnimationClass();
        btn2.jButtonXRight(10, 190, 10, 5, btnThis);

        //izq
        AnimationClass lbl11 = new AnimationClass();
        lbl11.jLabelXLeft(10, -200, 10, 5, lblFondoLogin);
        AnimationClass txt11 = new AnimationClass();
        txt11.jTextFieldXLeft(45, -120, 10, 5, txtUsuario);
        AnimationClass txt22 = new AnimationClass();
        txt22.jTextFieldXLeft(45, -120, 10, 5, txtcontrasena);
        AnimationClass lbl22 = new AnimationClass();
        lbl22.jLabelXLeft(70, -70, 10, 5, lblUsu);
        AnimationClass lbl33 = new AnimationClass();
        lbl33.jLabelXLeft(70, -90, 10, 5, lblContra);
        AnimationClass btn11 = new AnimationClass();
        btn11.jButtonXLeft(70, -80, 10, 5, btnAcceder);
        AnimationClass lbl44 = new AnimationClass();
        lbl44.jLabelXLeft(30, -155, 10, 5, lblOlv);
        AnimationClass lbl55 = new AnimationClass();
        lbl55.jLabelXLeft(75, -75, 10, 5, lblOlv2);
        AnimationClass lbl66 = new AnimationClass();
        lbl66.jLabelXLeft(50, -115, 10, 5, lblCue);
        AnimationClass lbl77 = new AnimationClass();
        lbl77.jLabelXLeft(75, -75, 10, 5, lblCue2);
        AnimationClass btn22 = new AnimationClass();
        btn22.jButtonXLeft(190, 10, 10, 5, btnThis);


    }//GEN-LAST:event_btnThisActionPerformed

    private void lblUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuMouseClicked

    }//GEN-LAST:event_lblUsuMouseClicked
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/aaaaaaa(1)"));

        return retValue;
    }
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        AnuncioAtras();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        AnuncioAdelante();
    }//GEN-LAST:event_btnAdelanteActionPerformed
    private void AnuncioAtras() {
        AnimationClass lbl8 = new AnimationClass();
        lbl8.jLabelXRight(0, 1160, 10, 5, lblAnuncio);
        AnimationClass lbl9 = new AnimationClass();
        lbl9.jButtonXRight(-500, 300, 10, 5, btnPI);
        AnimationClass lbl0 = new AnimationClass();
        lbl0.jLabelXRight(-800, 190, 10, 5, lblgame);
    }

    private void AnuncioAdelante() {
        AnimationClass lbl88 = new AnimationClass();
        lbl88.jLabelXLeft(1160, 0, 10, 5, lblAnuncio);
        AnimationClass lbl99 = new AnimationClass();
        lbl99.jButtonXLeft(300, -500, 10, 5, btnPI);
        AnimationClass lbl00 = new AnimationClass();
        lbl00.jLabelXLeft(190, -800, 10, 5, lblgame);
    }

    private void txtPass1FocusGained(java.awt.event.FocusEvent evt) {
        txtPass1.setEchoChar((char) 0);

    }

    private void txtPass1FocusLost(java.awt.event.FocusEvent evt) {
        txtPass1.setEchoChar('*');
    }

    private void txtPass2FocusGained(java.awt.event.FocusEvent evt) {
        txtPass2.setEchoChar((char) 0);
    }

    private void txtPass2FocusLost(java.awt.event.FocusEvent evt) {
        txtPass2.setEchoChar('*');
    }
    private void btnAcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcepActionPerformed
        String cad;
        String pwd = new String(txtPass1.getPassword());
        String pwd2 = new String(txtPass2.getPassword());
        String contrawa = "";
        if (txtNombre.getText().equals("") || txtApellido.getText().equals("") || txtCE.getText().equals("") || pwd.equals("") || pwd2.equals("")) {
            showMessageDialog(this, "Campo vacío, verifique los espacios");
            return;
        }
        if (Integer.parseInt(txtDia.getText()) > 31 || Integer.parseInt(txtDia.getText()) < 0) {
            showMessageDialog(this, "Error con los días, coloca un día valido");
            return;
        }
        if (Integer.parseInt(txtMes.getText()) > 12 || Integer.parseInt(txtMes.getText()) < 0) {
            showMessageDialog(this, "Error con los meses, coloca un mes valido");
            return;
        }
        if (Integer.parseInt(txtAnio.getText()) > 2001 || Integer.parseInt(txtAnio.getText()) < 0) {
            showMessageDialog(this, "Error con los años, coloca un año valido");
            return;
        }
        try {
            if (pwd.equals(pwd2)) {
                //validarFechaRegistrar();
                contrawa = pwd2;

            } else {
                showMessageDialog(this, "Sus contraseñas no coinciden");
                return;
            }
        } catch (RegistrarClienteException e) {
            showMessageDialog(this, e.getMessage());
            showMessageDialog(this, ":[[[[");
        }
        validaEmail(txtCE.getText());

        if (i == false) {
            showMessageDialog(this, "Ingresa un correo existente");
            return;
        }
        To = txtCE.getText();
        String ola = "100";
        int n = (int) (Math.random() * 1000);
        ola = ola + n + "";
        codigo = codigo + ola;
        mensaje = mensaje + codigo + "\n Gracias por registrarse en pump_it!";
        if (enviarCorreo() == true) {
            /*Verificar show= new Verificar();
            show.setVisible(true);*/
            Verificar.codigo = this.codigo;
            Verificar.IDbiblio = txtBiblio.getText();
            Verificar.nombre = txtNombre.getText();
            Verificar.AP = txtApellido.getText();
            //Verificar.AM=txtApellidoM.getText();
            Verificar.fech_nac = txtDia.getText() + "/" + txtMes.getText() + "/" + txtAnio.getText();
            Verificar.email = txtCE.getText();
            //Verificar.tel=txtTel.getText();
            Verificar.contraseña = contrawa;
            Verificar verif = new Verificar();
            verif.setVisible(true);
            this.dispose();
        } else {
            showMessageDialog(this, "Oye no:[");
            return;
        }
    }//GEN-LAST:event_btnAcepActionPerformed

    private void lblOlv2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlv2MouseClicked
        String con = "", idBiblio = "", nombre1 = "", amaterno = "", ap = "", fechan = "", correo1 = "", id = "";
        try {
            //idUsuario
            conectar();
            String cad = "select * from USUARIOS where nombre='" + txtUsuario.getText() + "'";
            st = conn.createStatement();
            st.execute(cad);

            rs = st.getResultSet();
            if (rs != null) {
                while (rs.next()) {
                    id = rs.getString("IdUsuario");
                    correoNuevo = rs.getString("correo");
                    con = rs.getString("pass");
                    showMessageDialog(this, correoNuevo);
                }
            } else {
                showMessageDialog(this, "No hay registros");
                st.close();
            }
        } catch (SQLException ex) {
            showMessageDialog(this, ex.getMessage());
        }
//            validaEmail(correoNuevo);
//        if(i==false){
//            showMessageDialog(this, "Ingresa un usuario que exista en los cuadros de texto");
//            return;
//        }
        To = correoNuevo;
        String ola = "100";
        int n = (int) (Math.random() * 1000);
        ola = ola + n + "";
        codigo = codigo + ola;
        mensaje = mensaje + con + "\n Gracias por utilizar Pump it!";
        if (enviarCorreo() == true) {
            showMessageDialog(this, "Revisa tu correo para recuperar contraseña");

        } else {
            return;
        }
    }

    private void lblOlvCMouseClicked(java.awt.event.MouseEvent evt) {
        /*String con="",id="",nombre1="",amaterno="",apaterno="",fechan="",correo1="",telef="";
        try {
            //idUsuario
            String cad="select * from Cliente where IdCliente='"+txtUsuario.getText()+"'";
            Statement stmt= cn.createStatement();
             stmt.executeQuery(cad);
             ResultSet rs=stmt.executeQuery(cad);
             
              while(rs.next()){
               id=rs.getString("IdCliente"); 
               correoNuevo=rs.getString("Email");  
               con=rs.getString("Psw"); 
             }
        }catch (SQLException ex) {
            showMessageDialog(this,ex.getMessage());
        }
            validaEmail(correoNuevo);
        if(i==false){
            showMessageDialog(this, "Ingresa un correo existente");
            return;
        }
        To=correoNuevo;
        String ola="100";
        int n=(int)(Math.random()*1000);
        ola=ola+n+"";
        codigo=codigo + ola;
        mensaje=mensaje+con+"\n Gracias por utilizar en Keeping the bar";
        if(enviarCorreo()==true){
            showMessageDialog(this,"Revisa tu correo para recuperar contraseña");

        }else{return;}*/
    }//GEN-LAST:event_lblOlv2MouseClicked

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) && (c < ',' || c > '.')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        int r = 0;
        String h = "";
        int b = (int) (Math.random() * 100);
        h = "700" + b + "";
        txtBiblio.setText(h);
    }//GEN-LAST:event_txtNombreMouseClicked

    private void lblCue2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCue2MouseClicked
        AnimationClass lbl11 = new AnimationClass();
        lbl11.jLabelXLeft(1160, 960, 10, 5, lblFondoLogin1);
        AnimationClass txt11 = new AnimationClass();
        txt11.jTextFieldXLeft(1160, 990, 10, 5, txtNombre);
        AnimationClass txt22 = new AnimationClass();
        txt22.jTextFieldXLeft(1160, 990, 10, 5, txtApellido);
        AnimationClass lbl22 = new AnimationClass();
        lbl22.jLabelXLeft(1160, 980, 10, 5, lblreg);
        AnimationClass lbl33 = new AnimationClass();
        lbl33.jLabelXLeft(1160, 990, 10, 5, lblUsua);
        AnimationClass btn11 = new AnimationClass();
        btn11.jButtonXLeft(1160, 1010, 10, 5, btnAcep);
        AnimationClass lbl44 = new AnimationClass();
        lbl44.jLabelXLeft(1160, 990, 10, 5, lblAP);
        AnimationClass lbl55 = new AnimationClass();
        lbl55.jLabelXLeft(1160, 990, 10, 5, lblFechNac);
        AnimationClass lbl66 = new AnimationClass();
        lbl66.jLabelXLeft(1160, 990, 10, 5, lblContra1);
        AnimationClass lbl77 = new AnimationClass();
        lbl77.jLabelXLeft(1160, 990, 10, 5, lblContra2);
        //txtPass1.setVisible(true);
        //txtPass2.setVisible(true);
        AnimationClass lbl88 = new AnimationClass();
        lbl88.jLabelXLeft(1160, 990, 10, 5, lblBiblio);
        AnimationClass lbl99 = new AnimationClass();
        lbl99.jLabelXLeft(1160, 990, 10, 5, lblCE);
        AnimationClass lbl1010 = new AnimationClass();
        lbl1010.jLabelXLeft(1160, 1020, 10, 5, lblunu);
        AnimationClass lbl1111 = new AnimationClass();
        lbl1111.jLabelXLeft(1160, 1070, 10, 5, lblawa);
        AnimationClass txta = new AnimationClass();
        txta.jTextFieldXLeft(1160, 990, 10, 5, txtDia);
        AnimationClass txtb = new AnimationClass();
        txtb.jTextFieldXLeft(1160, 1040, 10, 5, txtMes);
        AnimationClass txtc = new AnimationClass();
        txtc.jTextFieldXLeft(1160, 1090, 10, 5, txtAnio);
        AnimationClass txtd = new AnimationClass();
        txtd.jTextFieldXLeft(1160, 990, 10, 5, txtBiblio);
        AnimationClass txte = new AnimationClass();
        txte.jTextFieldXLeft(1160, 990, 10, 5, txtCE);
        AnimationClass psw1 = new AnimationClass();
        psw1.jPasswordFieldXLeft(1160, 990, 10, 5, txtPass1);
        AnimationClass psw2 = new AnimationClass();
        psw2.jPasswordFieldXLeft(1160, 990, 10, 5, txtPass2);

        //izq
        AnimationClass lbl1 = new AnimationClass();
        lbl1.jLabelXRight(960, 1160, 10, 5, lblFondoLogin1);
        AnimationClass txt1 = new AnimationClass();
        txt1.jTextFieldXRight(990, 1160, 10, 5, txtNombre);
        AnimationClass txt2 = new AnimationClass();
        txt1.jTextFieldXRight(990, 1160, 10, 5, txtApellido);
        AnimationClass lbl2 = new AnimationClass();
        lbl2.jLabelXRight(980, 1160, 10, 5, lblreg);
        AnimationClass lbl3 = new AnimationClass();
        lbl3.jLabelXRight(990, 1160, 10, 5, lblUsua);
        AnimationClass btn1 = new AnimationClass();
        btn1.jButtonXRight(1010, 1160, 10, 5, btnAcep);
        AnimationClass lbl4 = new AnimationClass();
        lbl4.jLabelXRight(990, 1160, 10, 5, lblAP);
        AnimationClass lbl5 = new AnimationClass();
        lbl5.jLabelXRight(990, 1160, 10, 5, lblFechNac);
        AnimationClass lbl6 = new AnimationClass();
        lbl6.jLabelXRight(990, 1160, 10, 5, lblContra1);
        AnimationClass lbl7 = new AnimationClass();
        lbl7.jLabelXRight(990, 1160, 10, 5, lblContra2);
        // txtPass1.setVisible(false);
        //txtPass2.setVisible(false);
        AnimationClass lbl8 = new AnimationClass();
        lbl8.jLabelXRight(990, 1160, 10, 5, lblBiblio);
        AnimationClass lbl9 = new AnimationClass();
        lbl9.jLabelXRight(990, 1160, 10, 5, lblCE);
        AnimationClass lbl10 = new AnimationClass();
        lbl10.jLabelXRight(1020, 1160, 10, 5, lblunu);
        AnimationClass lbl11o = new AnimationClass();
        lbl11o.jLabelXRight(1070, 1160, 10, 5, lblawa);
        AnimationClass txtaa = new AnimationClass();
        txtaa.jTextFieldXRight(990, 1160, 10, 5, txtDia);
        AnimationClass txtbb = new AnimationClass();
        txtbb.jTextFieldXRight(1040, 1160, 10, 5, txtMes);
        AnimationClass txtcc = new AnimationClass();
        txtcc.jTextFieldXRight(1090, 1160, 10, 5, txtAnio);
        AnimationClass txtdd = new AnimationClass();
        txtdd.jTextFieldXRight(990, 1160, 10, 5, txtBiblio);
        AnimationClass txtee = new AnimationClass();
        txtee.jTextFieldXRight(990, 1160, 10, 5, txtCE);
        AnimationClass psw11 = new AnimationClass();
        psw11.jPasswordFieldXRight(990, 1160, 10, 5, txtPass1);
        AnimationClass psw22 = new AnimationClass();
        psw22.jPasswordFieldXRight(990, 1160, 10, 5, txtPass2);
        //der

    }//GEN-LAST:event_lblCue2MouseClicked

    private void txtPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass2ActionPerformed
    /*
    private void txtPass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass1FocusGained
    */
    private void validaEmail(String correo) {
        Pattern pattern = Pattern.compile(PATTERN_EMAIL);
        Matcher matcher = pattern.matcher(correo);
        if (txtCE.getText().length() != 0) {
            if (matcher.matches() == false) {
                i = false;

            } else {
                i = true;
            }
        } else {
            i = false;
        }
    }

    public boolean enviarCorreo() {

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(correo, password);
            }
        });

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(correo));
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(To));
            message.setSubject(Subject);
            message.setText(mensaje);

            Transport.send(message);

            return true;
        } catch (MessagingException e) {
            showMessageDialog(this, "No fue posible enviar el correo");
            //lblError.setText("No fue posible enviar el código de verificación. Asegúrese de estar conectado a Internet.");
            return false;
        }
    }

    private boolean validarRegistrar() {

        boolean b = true;
        //float aVida = fecha();
        String pwd = new String(txtPass1.getPassword());
        String pwd2 = new String(txtPass2.getPassword());
        if (txtNombre.getText().equals("")) {//equals igualar cadenas
            b = false;
            txtNombre.requestFocus();
        } else if (pwd.equals("")) {//equals igualar cadenas
            b = false;

            txtPass1.requestFocus();
        } else if (pwd2.equals("")) {//equals igualar cadenas
            b = false;
            txtPass2.requestFocus();
        } else if (txtApellido.getText().equals("")) {//equals igualar cadenas
            b = false;
            txtApellido.requestFocus();
        } else if (txtBiblio.getText().equals("")) {//equals igualar cadenas
            b = false;
            txtBiblio.requestFocus();
        } else if (txtCE.getText().equals("")) {//equals igualar cadenas
            b = false;
            txtCE.requestFocus();
        }
        return b;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    private static final String PATTERN_EMAIL = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    boolean i;
    public static String correo = "darien1005@gmail.com";
    public static String password = "rmvazquez123";
    String mensaje = "Tu código de verificación es: ";
    String To = "";
    String Subject = "Código de verificación del Soporte de Pump_it!";
    String codigo = "";
    Connection cn;
    Statement stmt;
    DefaultTableModel m;
    DefaultTableModel b;
    DefaultTableModel v;
    private sonidos sound = new sonidos();
    private Statement st;
    private ResultSet rs;
    private Connection conn = null;
    private String msAccDB = "C:\\Users\\marva\\Dropbox (Tecnológico)\\ED\\Pump_it!\\src\\Data\\Pump_ItDB.accdb";
    private String dbURL = "jdbc:ucanaccess://" + msAccDB;
    public OLEImage oleImage = new OLEImage();
    //DefaultTableModel m;
    private String IdUsuario;
    public String idBiblio;
    public String nombre = "";
    public String ap = "";
    public String am = "";
    public String fechn = "";
    public String direc = "";
    public String telefono = "";
    public String contraseña = "";
    public String correoNuevo = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnAcep;
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnPI;
    private javax.swing.JButton btnThis;
    private javax.swing.JLabel lblAP;
    private javax.swing.JLabel lblAnuncio;
    private javax.swing.JLabel lblBiblio;
    private javax.swing.JLabel lblCE;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblContra1;
    private javax.swing.JLabel lblContra2;
    private javax.swing.JLabel lblCue;
    private javax.swing.JLabel lblCue2;
    private javax.swing.JLabel lblFechNac;
    private javax.swing.JLabel lblFondoLogin;
    private javax.swing.JLabel lblFondoLogin1;
    private javax.swing.JLabel lblOlv;
    private javax.swing.JLabel lblOlv2;
    private javax.swing.JLabel lblUsu;
    private javax.swing.JLabel lblUsua;
    private javax.swing.JLabel lblawa;
    private javax.swing.JLabel lblgame;
    private javax.swing.JLabel lblreg;
    private javax.swing.JLabel lblunu;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBiblio;
    private javax.swing.JTextField txtCE;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JPasswordField txtPass2;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtcontrasena;
    // End of variables declaration//GEN-END:variables
}
