/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.*;
import java.io.IOException;
import java.sql.*;
import java.util.*;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import static javax.swing.JOptionPane.showMessageDialog;
import sun.audio.AudioPlayer;
import AppPackage.AnimationClass;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;
import javax.mail.*;
import javax.swing.table.JTableHeader;
import sun.audio.AudioStream;
 /*
 * @author Marval
 */
public class Pump_It extends javax.swing.JFrame {
    /**
     * Creates new form Pump_It
     */
    public Pump_It() {
        initComponents();getContentPane().setBackground(Color.darkGray);
        JTableHeader th; 
        th = dgvJuegos.getTableHeader(); 
        Font fuente = new Font("Myriad Pro", Font.ITALIC, 20); 
        th.setFont(fuente); 
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono5.png")).getImage() );
        ImageIcon imagen = new ImageIcon("/imagenes/Vector_Azul.png");
        interfaz.conexion conectar = new interfaz.conexion();
        try{
            conectar.conectar();
            jmbConexion.setText("Status: Conectado :D");
        }catch(Exception ex){
              System.out.println("Error de conexión");
              jmbConexion.setText("Status: Error de Conexión.");
          }
        if(conectar.conectar()==true){
            jmbConexion.setText("Status: Conectado :D");
        }else{
            jmbConexion.setText("Status: no conectado");
        }
        //JPanelBase.setVisible(false);
        m = (DefaultTableModel) dgvJuegos.getModel();
        llenarVideoJuegos();
        try {
            wii=new FileInputStream(new File("src\\sonidos\\Wii.WAV"));
            sonido=new AudioStream(wii);
        AudioPlayer.player.start(sonido);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        dgvJuegos = new javax.swing.JTable();
        txtPass2 = new javax.swing.JPasswordField();
        txtPass1 = new javax.swing.JPasswordField();
        btnAcep = new javax.swing.JButton();
        txtCE = new javax.swing.JTextField();
        lblCE = new javax.swing.JLabel();
        txtBiblio = new javax.swing.JTextField();
        lblBiblio = new javax.swing.JLabel();
        lblContra2 = new javax.swing.JLabel();
        lblContra1 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        lblFechNac = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblAP = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblUsua = new javax.swing.JLabel();
        lblreg = new javax.swing.JLabel();
        lblFondoLogin1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnLibreria = new javax.swing.JButton();
        btnTienda = new javax.swing.JButton();
        btnForo = new javax.swing.JButton();
        btnCuenta = new javax.swing.JButton();
        btnJuega = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmbConexion = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 701, 463));
        setMaximumSize(new java.awt.Dimension(1160, 600));
        setMinimumSize(new java.awt.Dimension(1160, 600));
        setName("Pump it!"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1160, 600));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        getContentPane().setLayout(null);

        dgvJuegos.setBackground(new java.awt.Color(51, 51, 51));
        dgvJuegos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dgvJuegos.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        dgvJuegos.setForeground(new java.awt.Color(255, 153, 0));
        dgvJuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo"
            }
        ));
        dgvJuegos.setOpaque(false);
        dgvJuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvJuegosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dgvJuegos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 100, 270, 460);

        txtPass2.setText("jPasswordField1");
        txtPass2.setVisible(false);
        txtPass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPass2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPass2FocusLost(evt);
            }
        });
        txtPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass2);
        txtPass2.setBounds(1160, 310, 140, 30);

        txtPass1.setText("jPasswordField1");
        txtPass1.setVisible(false);
        txtPass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPass1FocusLost(evt);
            }
        });
        getContentPane().add(txtPass1);
        txtPass1.setBounds(1160, 250, 140, 30);

        btnAcep.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        btnAcep.setForeground(new java.awt.Color(255, 153, 51));
        btnAcep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plus-icon.png"))); // NOI18N
        btnAcep.setText("Aceptar");
        btnAcep.setContentAreaFilled(false);
        btnAcep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcepActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcep);
        btnAcep.setBounds(1160, 470, 100, 80);

        txtCE.setBackground(new java.awt.Color(51, 51, 51));
        txtCE.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtCE.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCE);
        txtCE.setBounds(1160, 430, 140, 30);

        lblCE.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblCE.setForeground(new java.awt.Color(255, 255, 255));
        lblCE.setText("Correo electronico:");
        getContentPane().add(lblCE);
        lblCE.setBounds(1160, 410, 120, 15);

        txtBiblio.setBackground(new java.awt.Color(51, 51, 51));
        txtBiblio.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtBiblio.setForeground(new java.awt.Color(255, 255, 255));
        txtBiblio.setEnabled(false);
        getContentPane().add(txtBiblio);
        txtBiblio.setBounds(1160, 370, 140, 30);

        lblBiblio.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblBiblio.setForeground(new java.awt.Color(255, 255, 255));
        lblBiblio.setText("IdBiblioteca:");
        getContentPane().add(lblBiblio);
        lblBiblio.setBounds(1160, 350, 110, 15);

        lblContra2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblContra2.setForeground(new java.awt.Color(255, 255, 255));
        lblContra2.setText("Confirma contraseña:");
        getContentPane().add(lblContra2);
        lblContra2.setBounds(1160, 290, 140, 15);

        lblContra1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblContra1.setForeground(new java.awt.Color(255, 255, 255));
        lblContra1.setText("Contraseña:");
        getContentPane().add(lblContra1);
        lblContra1.setBounds(1160, 230, 70, 15);

        txtMes.setBackground(new java.awt.Color(51, 51, 51));
        txtMes.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtMes.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtMes);
        txtMes.setBounds(1160, 190, 140, 30);

        lblFechNac.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblFechNac.setForeground(new java.awt.Color(255, 255, 255));
        lblFechNac.setText("Fecha de nacimiento:");
        getContentPane().add(lblFechNac);
        lblFechNac.setBounds(1160, 170, 150, 15);

        txtApellido.setBackground(new java.awt.Color(51, 51, 51));
        txtApellido.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellido);
        txtApellido.setBounds(1160, 130, 140, 30);

        lblAP.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblAP.setForeground(new java.awt.Color(255, 255, 255));
        lblAP.setText("Nombre Completo:");
        getContentPane().add(lblAP);
        lblAP.setBounds(1160, 110, 130, 15);

        txtNombre.setBackground(new java.awt.Color(51, 51, 51));
        txtNombre.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(1160, 70, 140, 30);

        lblUsua.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblUsua.setForeground(new java.awt.Color(255, 255, 255));
        lblUsua.setText("Usuario:");
        getContentPane().add(lblUsua);
        lblUsua.setBounds(1160, 40, 80, 20);

        lblreg.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        lblreg.setForeground(new java.awt.Color(255, 255, 255));
        lblreg.setText("Cuenta.");
        getContentPane().add(lblreg);
        lblreg.setBounds(1160, 0, 170, 40);

        lblFondoLogin1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        lblFondoLogin1.setForeground(new java.awt.Color(255, 255, 255));
        lblFondoLogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-negro-detalles-naranjas_1408-69.jpg"))); // NOI18N
        lblFondoLogin1.setText("z");
        lblFondoLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFondoLogin1MouseClicked(evt);
            }
        });
        getContentPane().add(lblFondoLogin1);
        lblFondoLogin1.setBounds(1160, 0, 200, 590);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnLibreria.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        btnLibreria.setForeground(new java.awt.Color(255, 153, 51));
        btnLibreria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Bag-icon.png"))); // NOI18N
        btnLibreria.setText("Librería");
        btnLibreria.setEnabled(false);
        btnLibreria.setFocusable(false);
        btnLibreria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLibreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibreriaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLibreria);

        btnTienda.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        btnTienda.setForeground(new java.awt.Color(255, 153, 51));
        btnTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Basket-icon.png"))); // NOI18N
        btnTienda.setText("Tienda");
        btnTienda.setFocusable(false);
        btnTienda.setIconTextGap(6);
        btnTienda.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiendaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTienda);

        btnForo.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        btnForo.setForeground(new java.awt.Color(255, 153, 51));
        btnForo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Chat-6-icon.png"))); // NOI18N
        btnForo.setText("Foro");
        btnForo.setFocusable(false);
        btnForo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnForo);

        btnCuenta.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        btnCuenta.setForeground(new java.awt.Color(255, 153, 51));
        btnCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Settings-2-icon.png"))); // NOI18N
        btnCuenta.setText("Cuenta");
        btnCuenta.setFocusable(false);
        btnCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCuenta);

        btnJuega.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        btnJuega.setForeground(new java.awt.Color(255, 153, 51));
        btnJuega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arrow-Next-2-icon.png"))); // NOI18N
        btnJuega.setText("¡Juega ya!");
        btnJuega.setEnabled(false);
        btnJuega.setFocusable(false);
        btnJuega.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnJuega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnJuega);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 1110, 73);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(401, 401, 401))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(310, 100, 710, 460);

        jMenu2.setText("Pump it!");

        mnuCerrarSesion.setText("Cerrar Sesión");
        mnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarSesionActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCerrarSesion);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSalir);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Ayuda");

        jmbConexion.setText("status:");
        jMenu4.add(jmbConexion);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void mnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarSesionActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuCerrarSesionActionPerformed
    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void btnTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiendaActionPerformed
        Nuevo_PumpTienda.id=id;
        Nuevo_PumpTienda.nombre=nombre;
        Nuevo_PumpTienda.apellido=apellido;
        Nuevo_PumpTienda.nacimiento=nacimiento;
        Nuevo_PumpTienda.pass=pass;
        Nuevo_PumpTienda.idBiblioteca=idBiblioteca;
        Nuevo_PumpTienda.correo=correo;
        Nuevo_PumpTienda ventana = new Nuevo_PumpTienda();
        ventana.show(true);
        AudioPlayer.player.stop(sonido);
        this.dispose();
    }//GEN-LAST:event_btnTiendaActionPerformed

    private void btnLibreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibreriaActionPerformed
        Pump_It ventana = new Pump_It();
        ventana.show(true);
        this.dispose();
    }//GEN-LAST:event_btnLibreriaActionPerformed

    private void btnForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForoActionPerformed
        Foro.id=id;
        Foro.nombre=nombre;
        Foro.apellido=apellido;
        Foro.nacimiento=nacimiento;
        Foro.pass=pass;
        Foro.idBiblioteca=idBiblioteca;
        Foro.correo=correo;
        Foro ventana = new Foro();
        ventana.show(true);
        AudioPlayer.player.stop(sonido);
        this.dispose();
    }//GEN-LAST:event_btnForoActionPerformed

    private void dgvJuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvJuegosMouseClicked
        btnJuega.setEnabled(true);
        int fila = dgvJuegos.getSelectedRow();
        juego=(dgvJuegos.getValueAt(fila, 0).toString());
        if(juego.equals("Geometry Wars")){
             try {
            Image img = ImageIO.read(getClass().getResource("/imagenes/19116914790_254033af20_b.jpg"));
            lblImagen.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            showMessageDialog(this,ex.getMessage());
        }
        }else if(juego.equals("Osu!")){
             try {
            Image img = ImageIO.read(getClass().getResource("/imagenes/osu_game_screenshot.jpg"));
           lblImagen.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            showMessageDialog(this,ex.getMessage());
        }
        }else if(juego.equals("LIMBO")){
             try {
            Image img = ImageIO.read(getClass().getResource("/imagenes/limbo-img-4.jpg"));
            lblImagen.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            showMessageDialog(this,ex.getMessage());
        }
        }else if(juego.equals("DEFCON")){
             try {
            Image img = ImageIO.read(getClass().getResource("/imagenes/dc-25-website-header-2-900x506.png"));
            lblImagen.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            showMessageDialog(this,ex.getMessage());
        }
        }else if(juego.equals("Papers, Please")){
             try {
            Image img = ImageIO.read(getClass().getResource("/imagenes/ss_c133e1bf1da17a3f3719c74696c61da23e38eefe.1920x1080.jpg"));
            lblImagen.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            showMessageDialog(this,ex.getMessage());
        }
        }else if(juego.equals("Sora")){
             try {
            Image img = ImageIO.read(getClass().getResource("/imagenes/Sora-no-game-no-life-anime-37119012-1280-720.jpg"));
            lblImagen.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            showMessageDialog(this,ex.getMessage());
        }
        }else if(juego.equals("Project64")){
             try {
            Image img = ImageIO.read(getClass().getResource("/imagenes/Project64-Nintendo-64-Emulator-cover-Inmortalgame.jpg"));
            lblImagen.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            showMessageDialog(this,ex.getMessage());
        }
        }else if(juego.equals("Winkawaks")){
             try {
            Image img = ImageIO.read(getClass().getResource("/imagenes/maxresdefault (1).jpg"));
            lblImagen.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            showMessageDialog(this,ex.getMessage());
        }
        }else showMessageDialog(this,"No hay ningun juego para seleccionar, entre a la tienda para agregar juegos");
        
            
    }//GEN-LAST:event_dgvJuegosMouseClicked

    private void btnJuegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegaActionPerformed
        sonidos s = new sonidos();
        
        if(juego.equals("Geometry Wars")){
             try {
                Runtime.getRuntime().exec("C:\\Users\\marva\\Desktop\\pump_It_Catalogo\\GeometryWars\\GeometryWars.exe");
                sound.PumpItGameRunSound();
        } catch (IOException ex) {
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else if(juego.equals("Osu!")){
            try {
                Runtime.getRuntime().exec("C:\\Users\\marva\\AppData\\Local\\osu!\\osu!.exe");
                sound.PumpItGameRunSound();
        } catch (IOException ex) {
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else if(juego.equals("LIMBO")){
            try {
                Runtime.getRuntime().exec("C:\\Users\\marva\\Desktop\\pump_It_Catalogo\\LIMBO\\limbo.exe");
                sound.PumpItGameRunSound();
        } catch (IOException ex) {
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else if(juego.equals("DEFCON")){
            try {
                Runtime.getRuntime().exec("C:\\Users\\marva\\Desktop\\pump_It_Catalogo\\DEFCON\\Defcon\\Defcon\\defcon.exe");
                sound.PumpItGameRunSound();
        } catch (IOException ex) {
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else if(juego.equals("Papers, Please")){
             try {
                Runtime.getRuntime().exec("C:\\Users\\marva\\Desktop\\pump_It_Catalogo\\Papers, Please\\PapersPlease.exe");
                sound.PumpItGameRunSound();
        } catch (IOException ex) {
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else if(juego.equals("Sora")){
             try {
                Runtime.getRuntime().exec("C:\\Users\\marva\\Desktop\\pump_It_Catalogo\\Sora\\sora.exe");
                sound.PumpItGameRunSound();
        } catch (IOException ex) {
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else if(juego.equals("Project64")){
            try {
                Runtime.getRuntime().exec("C:\\Users\\marva\\Desktop\\pump_It_Catalogo\\Project 64 1.6\\Project64.exe");
                sound.PumpItGameRunSound();
        } catch (IOException ex) {
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else if(juego.equals("Winkawaks")){
            try {
                Runtime.getRuntime().exec("C:\\Users\\marva\\Desktop\\pump_It_Catalogo\\winkawaks159\\WinKawaks.exe");
                sound.PumpItGameRunSound();
        } catch (IOException ex) {
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else showMessageDialog(this,"No hay ningun juego para seleccionar, entre a la tienda para agregar juegos");
        sound.PumpItGameRunSound();
        AudioPlayer.player.stop(sonido);
    }//GEN-LAST:event_btnJuegaActionPerformed

    private void lblFondoLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoLogin1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFondoLogin1MouseClicked

    private void txtPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass2ActionPerformed

    private void btnAcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcepActionPerformed
        try{
             String pwd = new String(txtPass1.getPassword());
            String pwd2 = new String(txtPass2.getPassword());
            if(pwd.equals(pwd2)){
            conectar();
            String nuevoNombre = txtNombre.getText();//usuario
            String nuevoApellido = txtApellido.getText();//nombre del usuario
            String nuevoNacimiento = txtMes.getText();
            String nuevoCE = txtCE.getText();
            String nuevoPass = txtPass1.getText();
            String sql;
            sql="update USUARIOS set nombre='"+nuevoNombre+"',apellido='"+nuevoApellido+"' ,nacimiento='"+nuevoNacimiento+"',pass='"+nuevoPass+"'where nombre='"+nuevoNombre+"'";
            st.execute(sql);
            }else{showMessageDialog(this,"Las contraseñas no coinciden.");}//IdBiblioteca
        }catch(SQLException ex){
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAcepActionPerformed

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) && (c < ',' || c > '.')) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
      /*  int r = 0;
        String h = "";
        int b = (int) (Math.random() * 100);
        h = "700" + b + "";
        txtBiblio.setText(h);*/
    }//GEN-LAST:event_txtNombreMouseClicked
    
    private void btnCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaActionPerformed
         txtNombre.setText(nombre);
         txtApellido.setText(apellido);
         txtMes.setText(nacimiento);
         txtBiblio.setText(idBiblioteca);
         txtCE.setText(correo);
         txtPass1.setText(pass);
        
        AnimationClass lbl11 = new AnimationClass();
        lbl11.jLabelXLeft(1160,960,10,5, lblFondoLogin1);
        AnimationClass txt11 = new AnimationClass();
        txt11.jTextFieldXLeft(1160,990,10,5, txtNombre);
        AnimationClass txt22 = new AnimationClass();
        txt22.jTextFieldXLeft(1160,990,10,5, txtApellido);
        AnimationClass lbl22 = new AnimationClass();
        lbl22.jLabelXLeft(1160,980,10,5, lblreg);
        AnimationClass lbl33 = new AnimationClass();
        lbl33.jLabelXLeft(1160,990,10,5, lblUsua);
        AnimationClass btn11 = new AnimationClass();
        btn11.jButtonXLeft(1160,1010,10,5, btnAcep);
        AnimationClass lbl44 = new AnimationClass();
        lbl44.jLabelXLeft(1160,990,10,5, lblAP);
        AnimationClass lbl55 = new AnimationClass();
        lbl55.jLabelXLeft(1160,990,10,5, lblFechNac);
        AnimationClass lbl66 = new AnimationClass();
        lbl66.jLabelXLeft(1160,990,10,5, lblContra1);
        AnimationClass lbl77 = new AnimationClass();
        lbl77.jLabelXLeft(1160,990,10,5, lblContra2);
        txtPass1.setVisible(true);
        txtPass2.setVisible(true);
        AnimationClass lbl88 = new AnimationClass();
        lbl88.jLabelXLeft(1160,990,10,5, lblBiblio);
        AnimationClass lbl99 = new AnimationClass();
        lbl99.jLabelXLeft(1160,990,10,5, lblCE);
        AnimationClass lbl1010 = new AnimationClass();
        AnimationClass txtb = new AnimationClass();
        txtb.jTextFieldXLeft(1160,1040,10,5, txtMes);
        AnimationClass txtd = new AnimationClass();
        txtd.jTextFieldXLeft(1160,990,10,5, txtBiblio);
        AnimationClass txte = new AnimationClass();
        txte.jTextFieldXLeft(1160,990,10,5, txtCE);
        AnimationClass psw1 = new AnimationClass();
        psw1.jPasswordFieldXLeft(1160, 990, 10, 5, txtPass1);
        AnimationClass psw2 = new AnimationClass();
        psw2.jPasswordFieldXLeft(1160, 990, 10,5, txtPass2);
        
        //izq
        AnimationClass lbl1 = new AnimationClass();
        lbl1.jLabelXRight(960,1160,10,5, lblFondoLogin1);
        AnimationClass txt1 = new AnimationClass();
        txt1.jTextFieldXRight(990,1160,10,5, txtNombre);
        AnimationClass txt2 = new AnimationClass();
        txt1.jTextFieldXRight(990,1160,10,5, txtApellido);
        AnimationClass lbl2 = new AnimationClass();
        lbl2.jLabelXRight(980,1160,10,5, lblreg);
        AnimationClass lbl3 = new AnimationClass();
        lbl3.jLabelXRight(990,1160,10,5, lblUsua);
        AnimationClass btn1 = new AnimationClass();
        btn1.jButtonXRight(1010,1160,10,5, btnAcep);
        AnimationClass lbl4 = new AnimationClass();
        lbl4.jLabelXRight(990,1160,10,5, lblAP);
        AnimationClass lbl5 = new AnimationClass();
        lbl5.jLabelXRight(990,1160,10,5, lblFechNac);
        AnimationClass lbl6 = new AnimationClass();
        lbl6.jLabelXRight(990,1160,10,5, lblContra1);
        AnimationClass lbl7 = new AnimationClass();
        lbl7.jLabelXRight(990,1160,10,5, lblContra2);
        //txtPass1.setVisible(false);
        //txtPass2.setVisible(false);
        AnimationClass lbl8 = new AnimationClass();
        lbl8.jLabelXRight(990,1160,10,5, lblBiblio);
        AnimationClass lbl9 = new AnimationClass();
        lbl9.jLabelXRight(990,1160,10,5, lblCE);
        AnimationClass lbl10 = new AnimationClass();
        AnimationClass txtbb = new AnimationClass();
        txtbb.jTextFieldXRight(1040,1160,10,5, txtMes);
        AnimationClass txtdd = new AnimationClass();
        txtdd.jTextFieldXRight(990,1160,10,5, txtBiblio);
        AnimationClass txtee = new AnimationClass();
        txtee.jTextFieldXRight(990,1160,10,5, txtCE);
        AnimationClass psw11 = new AnimationClass();
        psw11.jPasswordFieldXRight(990,1160,10,5, txtPass1);
        AnimationClass psw22 = new AnimationClass();
        psw22.jPasswordFieldXRight(990,1160,10,5, txtPass2);
    }//GEN-LAST:event_btnCuentaActionPerformed

    private void txtPass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass1FocusGained
        txtPass1.setEchoChar((char)0);
        
    }//GEN-LAST:event_txtPass1FocusGained

    private void txtPass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass1FocusLost
        txtPass1.setEchoChar('*');
    }//GEN-LAST:event_txtPass1FocusLost

    private void txtPass2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass2FocusGained
        txtPass2.setEchoChar((char)0);
    }//GEN-LAST:event_txtPass2FocusGained

    private void txtPass2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass2FocusLost
        txtPass2.setEchoChar('*');
    }//GEN-LAST:event_txtPass2FocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
       AudioPlayer.player.start(sonido);
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        AudioPlayer.player.stop(sonido);
    }//GEN-LAST:event_formFocusLost
    
    private void llenarVideoJuegos(){
        try{
        conectar();
        Object O[]=new Object[4];
        st=conn.createStatement();
        st.execute("select nombre, rating, desarrolladora from VIDEOJUEGOS where IdBiblioteca = "+idBiblioteca);
        rs = st.getResultSet();
        m.setRowCount(0);
        if(rs!=null && rs.isFirst()==false)
        {
            while(rs.next()){
                O[0]=rs.getString("Nombre");
                O[1]=rs.getInt("Rating");
                O[2]=rs.getString("Desarrolladora");
                m.addRow(O);
            }
        }
        else{
            showMessageDialog(this,"Error, no se encontraron registros");
            st.close();
        }
        }catch(SQLException ex){
            Logger.getLogger(Pump_It.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pump_It.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pump_It.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pump_It.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pump_It.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pump_It().setVisible(true);
                
                
            }
        });
    }
    public void conectar(){
      try {
         
         Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
         
         
      }
      catch(ClassNotFoundException cnfex) {
      
         System.out.println("Problema al cargar o "
                + "registrar:  MS Access JDBC driver");
         cnfex.printStackTrace();
      }
      
      try{
         conn = DriverManager.getConnection(dbURL);
         st=conn.createStatement();
         System.out.println("Conexion establecida");
         
      }
      catch(SQLException ex){
       
         System.out.println("error de conexion");
      }
      System.out.println("Proceso de conexión finalizado.");
   }
    
    public void aparecerocontrasenas() {
        Timer t = new Timer();
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                txtPass1.setVisible(true);
                txtPass1.setVisible(false);
            }
        };
        t.schedule(task, 3000);
    }

    public static String juego="";
    private sonidos sound = new sonidos();
    private Statement st;
    private ResultSet rs;
    private Connection conn = null;
    private String msAccDB = "C:\\Users\\marva\\Dropbox (Tecnológico)\\ED\\Pump_it!\\src\\Data\\Pump_ItDB.accdb";
    private String dbURL = "jdbc:ucanaccess://"+msAccDB;
    public OLEImage oleImage = new OLEImage();
    DefaultTableModel m;
    private  String IdUsuario;
    public static String id="";
    public static String nombre="";
    public static String apellido="";
    public static String nacimiento="";
    public static String pass="";
    public static String idBiblioteca="";
    public static String correo="";
    InputStream ouf,wii;
    AudioStream sonido;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcep;
    private javax.swing.JButton btnCuenta;
    private javax.swing.JButton btnForo;
    private javax.swing.JButton btnJuega;
    private javax.swing.JButton btnLibreria;
    private javax.swing.JButton btnTienda;
    private javax.swing.JTable dgvJuegos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem jmbConexion;
    private javax.swing.JLabel lblAP;
    private javax.swing.JLabel lblBiblio;
    private javax.swing.JLabel lblCE;
    private javax.swing.JLabel lblContra1;
    private javax.swing.JLabel lblContra2;
    private javax.swing.JLabel lblFechNac;
    private javax.swing.JLabel lblFondoLogin1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblUsua;
    private javax.swing.JLabel lblreg;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBiblio;
    private javax.swing.JTextField txtCE;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JPasswordField txtPass2;
    // End of variables declaration//GEN-END:variables
}
