/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import javax.swing.ImageIcon;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Verificar extends javax.swing.JFrame {

    /**
     * Creates new form Verificar
     */
    public Verificar() {
        initComponents();
        conectar();
        this.getContentPane().setBackground(Color.DARK_GRAY);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono5.png")).getImage() );
        
    }
    public void conectar(){
      try {
         
         Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
         
         
      }
      catch(ClassNotFoundException cnfex) {
      
         System.out.println("Problema al cargar o "
                + "registrar:  MS Access JDBC driver");
         cnfex.printStackTrace();
      }
      
      try{
         conn = DriverManager.getConnection(dbURL);
         st=conn.createStatement();
         System.out.println("Conexion establecida");
         
      }
      catch(SQLException ex){
       
         System.out.println("error de conexion");
      }
      System.out.println("Proceso de conexión finalizado.");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtVerificar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Verificación");

        btnAceptar.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 153, 51));
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plus-icon.png"))); // NOI18N
        btnAceptar.setText("¡Termina el registro!");
        btnAceptar.setToolTipText("");
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plus-icon2.png"))); // NOI18N
        btnAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plus-icon (4).png"))); // NOI18N
        btnAceptar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plus-icon (4).png"))); // NOI18N
        btnAceptar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plus-icon2.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Verificación del usuario.");

        txtVerificar.setBackground(new java.awt.Color(51, 51, 51));
        txtVerificar.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        txtVerificar.setForeground(new java.awt.Color(255, 153, 0));

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Código de verificación:");

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¡Recuerda que todo es por tu seguridad y la de tus datos!");

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Se ha enviado a tu correo un codigo de verificación.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(txtVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(172, 172, 172)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(182, 182, 182)
                            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(144, 144, 144)
                            .addComponent(jLabel1))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String cad="";
        String ola="1000";
        int n=(int)(Math.random()*100000);
        ola=ola+n+"";
        String ola2="2039";
        int n2=(int)(Math.random()*100000);
        ola2=ola2+n2+"";
        try{
             if(txtVerificar.getText().equals("")){
            showMessageDialog(this, "Debes ingresar tu código, verifica tu correo electronico");
            txtVerificar.requestFocus();
            return;
        }
        if(!txtVerificar.getText().equals(codigo)){
            showMessageDialog(this, "El código de verificaciòn no es correcto, verifica tu correo");
            txtVerificar.requestFocus();
            return;
        }
        
            cad = "insert into USUARIOS(idUsuario,nombre,apellido, nacimiento, pass,idBiblioteca,correo) Values('"+
                           ola + "','" + nombre + "','"+ AP +"','"+ fech_nac +"','"+contraseña+"','" + IDbiblio + "','"+ email +"')";
                    conectar();
                    st.execute(cad);
                    System.out.println("inserted");
                    st.close();
                    Login Login=new Login();
                    Login.setVisible(true);
                    this.dispose();
                    showMessageDialog(this, "¡Se ha creado con exito!");
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(RegistrarClienteException.class.getName()).log(Level.SEVERE, null, ex);
                    showMessageDialog(this, "Ha ocurrido un error, vuelva a interntarlo");
                }
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verificar().setVisible(true);
            }
        });
    }
    public static String codigo="";
    public static String IDbiblio="";
    public static String nombre="";
    public static String AP="";
    public static String AM="";
    public static String fech_nac="";
    public static String email="";
    public static String tel="";
    public static String contraseña="";
     private sonidos sound = new sonidos();
    private Statement st;
    private ResultSet rs;
    private Connection conn = null;
    private String msAccDB = "C:\\Users\\marva\\Dropbox (Tecnológico)\\ED\\Pump_it!\\src\\Data\\Pump_ItDB.accdb";
    private String dbURL = "jdbc:ucanaccess://"+msAccDB;
    public OLEImage oleImage = new OLEImage();
    DefaultTableModel m;
    private  String IdUsuario;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtVerificar;
    // End of variables declaration//GEN-END:variables
}
